RAIN-1241 Added README.md and LOCALSETUP.md file for egov-persister s…
egovernments/core-services pull request #272
Opened 2020-08-17 19:13 UTC by rohit-eGov

…ervice

2020-09-15 06:05 UTC, tarunlalwani requested changes

2020-09-15 06:05 UTC, tarunlalwani commented on egov-persister/LOCALSETUP.md
> +   we have to add `file://` as prefix. for example: `egov.persist.yml.repo.path = file:///home/rohit/Documents/configs/egov-persister/abc-persister.yml`. If there are multiple file seperate it with `
Talk about folder path also, these properties can load the whole folder as well. Please check confirm and update the document

2020-09-15 06:05 UTC, tarunlalwani commented on egov-persister/LOCALSETUP.md
> +    - spring.datasource.url=jdbc:postgresql://localhost:5432/[localDB]
No talk about database

2020-09-24 14:45 UTC, sathishp-eGov commented
@rohit-eGov please check.

2020-09-25 07:02 UTC, tarunlalwani approved these changes

2020-09-25 07:02 UTC, tarunlalwani approved these changes

2020-09-25 07:02 UTC, merged